# Generated by Django 5.2.7 on 2025-10-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_nominale', models.CharField(max_length=50)),
                ('anno_conio', models.IntegerField()),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monete', to='accounts.stato')),
            ],
        ),
        migrations.CreateModel(
            name='Esemplare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esemplari', to=settings.AUTH_USER_MODEL)),
                ('luogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esemplari', to='accounts.luogo')),
                ('moneta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esemplari', to='accounts.moneta')),
            ],
        ),
    ]
